### ISSUE TITLE
Feature .diffignore

### ISSUE THREAD

**Issue by jrauschenbusch** [dotenv-linter/dotenv-linter#773]
For more advanced compare operations like in GitOps repositories and automated environment promotion it‘s often required to exclude known but accepted differences.

It would be really good to have a mechanism like a .gitignore file, but for diffs. Furthermore it would be good to be able to exclude files and just subset of env vars of a file.

Maybe in TOML

```toml
[[excludes]]
path = "/path/to/.env"
keys = [ "EXCLUDED_1", "^EXCLUDED_.*$" ]

[[excludes]]
path = "/path/toc/other/**/.env"
```

YAML:
```yaml
excludes:
  - path: /path/to/.env
    keys:
    - EXCLUDED_1
    - ^EXCLUDED_.*$
  - path: /path/to/other/**/.env
```
