### ISSUE TITLE
Feature request: pre-commit hooks 

### ISSUE THREAD

**Issue by desenhar** [dotenv-linter/dotenv-linter#787]
Hi,

I'd like to use dotenv-linter as a pre commit hook, something like this

 ```
repos:
  - repo: https://github.com/dotenv-linter/dotenv-linter
    rev: 3.3.0  
    hooks:
      - id: dotenv-linter
        args: [--skip QuotedCharacter ]
```

As I understand this shouldn't be too difficult to implement and I'd be happy to create a PR.

Please let me know if this is something that would be possible.
